steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/utility-binder-434801-u8/flask-app:$COMMIT_SHA'
      - '.'

  # Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/utility-binder-434801-u8/flask-app:$COMMIT_SHA'

  # Step 3: Deploy to Google Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'docker-container-instance'
      - '--zone'
      - 'us-central1-a'
      - '--container-image'
      - 'gcr.io/utility-binder-434801-u8/flask-app:$COMMIT_SHA'
      - '--container-restart-policy'
      - 'always'

images:
  - 'gcr.io/utility-binder-434801-u8/flask-app:$COMMIT_SHA'

# Substitutions allow you to define variables like the commit SHA
substitutions:
  _COMMIT_SHA: $BUILD_ID  # This represents the commit SHA automatically provided in Cloud Build

# Options for the Cloud Build setup
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET